image: corise/sql-course-gitpod
tasks:
  - init: |
      ./gitpod-init.sh
    command: |
      ./gitpod-command.sh
ports:
  - port: 8000
    onOpen: open-browser
  - port: 8081
    onOpen: open-browser
  - port: 5432
    onOpen: ignore
